server:
  port: 9000
spring:
  application:
      name: edge-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-With-Eureka: true
    fetch-Registry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
zuul:
  ignoredServices: "*"
  routes:
    customer-service:
      path: /customer-service/**

security:
  oauth2:
    resource:
      userInfoUri: http://auth-service:8181/uaa/user
