server:
  port: 0
spring:
  profiles: docker
  application:
      name: customer-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/dev?useSSL=false
    username: root
    password: dbpass
  jpa:
     hibernate:
       dialect: org.hibernate.dialect.MySQL5Dialect
       ddl-auto: update
     show-sql: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-With-Eureka: true
    fetch-Registry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
